export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";
export const CREATE_POST_LOADING = "CREATE_POST_LOADING";
export const CREATE_POST_RESET = "CREATE_POST_RESET";
