export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED";
export const CREATE_COMMENT_LOADING = "CREATE_COMMENT_LOADING";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";
